import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import '../services/service_locator.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations? of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations);
  }

  static const List<String> supportedLanguages = ['en', 'ku', 'ar'];

  static final Map<String, Map<String, String>> _localizedValues = {
    'ku': {
      'app_name': 'پەرتوک',
      'tagline': 'پوختەی ئاستی بەرز و فێربوونی خێرا',
      'splash_subtitle': 'بە زیرەکی فێربە، خێراتر پێش بکەوە',
      'onboarding_title_1': 'ئاستی زانستی جیهانی',
      'onboarding_desc_1': 'توانای بەدەست گەیشتن لە باشترین کتێبەکانی جیهان بە دەق و دەنگی بەرزکوالێتی.',
      'onboarding_title_2': 'گەشەکردن لە ١٥ خولەکدا',
      'onboarding_desc_2': 'کاتەکەت باشتر بەکاربهێنە. پوختەی کتێبەکان بخوێنەوە یان گوێی لێ بگرە لە کاتی هاتووچۆ یان پشوودان.',
      'onboarding_title_3': 'تایبەت بۆ تۆ',
      'onboarding_desc_3': 'پێشنیاری ڕۆژانە، پوختەی گونجاو و ڕێگای فێربوونی تایبەت.',
      'get_started': 'دەست پێ بکە',
      'next': 'دواتر',
      'skip': 'تێپەڕە',
      'select_language': 'زمان هەڵبژێرە',
      'english': 'ئینگلیزی',
      'kurdish': 'کوردی (سۆرانی)',
      'arabic': 'عەرەبی',
      'login': 'چوونەژوورەوە',
      'register': 'تۆمارکردن',
      'email': 'ناونیشانی ئیمەیڵ',
      'password': 'وشەی نهێنی',
      'fullname': 'ناوی تەواو',
      'forgot_password': 'وشەی نهێنیت لەبیر چووە؟',
      'login_with_google': 'بە Google بەردەوام بە',
      'login_with_apple': 'بە Apple بەردەوام بە',
      'continue_as_guest': 'وەک میوان بەردەوام بە',
      'dont_have_account': 'هەژمارت نییە؟ تۆمار بکە',
      'already_have_account': 'هەژمارت هەیە؟ بچۆ ژوورەوە',
      'select_interests': 'حەز و بەرژەوەندییەکانت چین؟',
      'interests_subtitle': 'ئەزموونی فێربوونت لەسەر بنەمای ئەمانە ڕێکدەخەین.',
      'select_goals': 'ئامانجەکانی فێربوونت هەڵبژێرە',
      'goals_subtitle': 'ئامانجی ڕۆژانە بۆ فێربوونی کورت دابنێ.',
      'save_continue': 'پاشەکەوت بکە و بەردەوام بە',
      'home': 'سەرەکی',
      'explore': 'دۆزینەوە',
      'search': 'گەڕان',
      'library': 'کتێبخانەی من',
      'reader_settings': 'ڕێکخستنی خوێنەر',
      'font_size': 'قەبارەی نووسین',
      'reader_theme': 'ڕوکاری خوێندنەوە',
      'profile': 'پرۆفایل',
      'daily_digest': 'پوختەی ڕۆژانە',
      'digest_subtitle': 'خوێندنەوەی هەڵبژێردراوی ١٥ خولەکی ئەمڕۆت',
      'mood_suggestions': 'ئەمڕۆ چۆن هەست دەکەیت؟',
      'mood_ambitious': 'پڕ ئامانج',
      'mood_tired': 'ماندوو',
      'mood_curious': 'بە پەرۆش',
      'mood_stressed': 'فشاردار',
      'streak_title': 'زنجیرەی فێربوون',
      'streak_desc': 'هەموو ڕۆژێک فێربە بۆ پاراستنی زنجیرەی فێربوونت.',
      'days_streak': 'تۆماری بەردەوام',
      'categories': 'پۆلەکان',
      'saved_summaries': 'پوختە پاشەکەوتکراوەکان',
      'downloads': 'داگرتنەکان',
      'notes_highlights': 'تێبینی و نیشانکردنەکان',
      'learning_paths': 'ڕێگاکانی فێربوون',
      'achievements': 'دەستکەوتەکان',
      'settings': 'ڕێکخستنەکان',
      'admin_dashboard': 'پەڕەی بەڕێوەبەر',
      'premium_subscription': 'بەشداربوونی پڕیمیۆم',
      'go_premium': 'بەرزکردنەوە بۆ پڕیمیۆم',
      'go_premium_desc': 'گەشتنبە پوختەی بێ سنوور، گێڕانەوەی دەنگی، داگرتنی ئۆفلاین.',
      'start_free_trial': 'تاقیکردنەوەی خۆڕایی',
      'restore_purchases': 'گەڕاندنەوەی هەژماری پریمێوم',
      'book_details': 'زانیاریی کتێب',
      'read_summary': 'پوختە بخوێنەوە',
      'listen_audio': 'گوێ لە دەنگ بگرە',
      'five_min_summary': 'پوختەی ٥ خولەکی',
      'fifteen_min_summary': 'پوختەی ١٥ خولەکی',
      'chapters': 'خاڵە سەرەکییەکان',
      'key_ideas': 'بیرۆکە سەرەکییەکان',
      'keypoints_count': '{count} بیرۆکەی سەرەکی',
      'key_quotes': 'وتە گرنگەکان',
      'action_points': 'هەنگاوە جێبەجێکاریەکان',
      'ai_coach': 'ڕاهێنەری فێربوونی زیرەکی دەستکرد',
      'ask_coach': 'پرسیارێک لە ڕاهێنەر بکە...',
      'comparison': 'بەراوردی کتێبەکان',
      'quiz': 'تاقیکردنەوە بکە',
      'flashcards': 'فلاشکاردەکان بخوێنەرەوە',
      'add_note': 'تێبینی زیاد بکە',
      'highlights': 'نیشانکردنەکان',
      'my_notes': 'تێبینییەکانی من',
      'daily_streak': 'زنجیرەی ڕۆژانە',
      'settings_dark_mode': 'ڕووکاری تاریک',
      'settings_light_mode': 'ڕووکاری ڕووناک',
      'settings_notifications': 'ئاگادارکردنەوەکان',
      'settings_family': 'هەژمارەکانی پلانی خێزان',
      'voice_narration': 'دەنگی وەرگێڕ',
      'save_goal': 'وەک ئامانجی کەسی پاشەکەوت بکە',
      'completed': 'تەواوبوو',
      'progress': 'پێشکەوتن',
      'certificate': 'بڕوانامە',
      'congratulations': 'پیرۆزبایی!',
      'cert_desc': 'بە سەرکەوتوویی ئەم ڕێگای فێربوونەت تەواو کرد.',
      'save': 'پاشەکەوت بکە',
      'cancel': 'هەڵوەشاندنەوە',
      'add_new_book': 'کتێبێکی نوێ باربکە',
      'admin_mode': 'دۆخی بەڕێوەبەر',
      'title': 'ناونیشان',
      'author': 'نووسەر',
      'audio_url': 'URL دەنگ',
      'category': 'پۆل',
      'is_premium_q': 'ئەمە پڕیمیۆمە؟',
      'upload': 'ناوەڕۆک باربکە',
      'unlock_full_book': 'کتێبی تەواو بکەرەوە',
      'guest_restriction_desc': 'ئەکاونتە میوانەکان تەنها دەستیان بە دوو خاڵی سەرەکی یەکەم دەگات. ئەکاونتێکی بێ بەرامبەر دروست بکە بۆ گوێگرتن لە تەواوی کتێبەکە.',
      'maybe_later': 'لەوانەیە دواتر',
      'chapter': 'خاڵی سەرەکی',
      'exit_title': 'دەرچوون لە ئەپ',
      'exit_desc': 'دڵنیایت لە دەرچوون لە ئەپەکە؟',
      'exit_btn': 'دەرچوون',
      'cancel_btn': 'هەڵوەشاندنەوە',
      'register_now': 'ئێستا تۆمار بکە',
      'continue_reading': 'بەردەوام بە لە خوێندنەوە',
      'liked': 'دڵخوازەکان',
      'one_idea_per_day': 'یەک بیرۆکە لە ڕۆژێکدا',
      'my_learning_hub': 'ناوەندی فێربوونی من',
      'system_settings': 'ڕێکخستنەکانی سیستم',
      'sign_out': 'چوونەدەرەوە',
      'popular_searches': 'گەڕانە باوەکان',
      'recent_searches': 'گەڕانەکانی پێشوو',
      'new_releases': 'بڵاوکراوە نوێیەکان',
      'trending': 'باوەکان',
      'editor_picks': 'هەڵبژاردەکانی سەرنووسەر',
      'min_read': 'خولەک خوێندنەوە',
      'streak': 'رۆژ لەسەریەک',
      'ach_books_desc': '@count کتێب تەواو بکە',
      'ach_streak_desc': 'بۆ ماوەی @count ڕۆژ لەسەریەک بەردەوام بە',
      'ach_saved_desc': '@count کتێب لە کتێبخانەکەت پاشەکەوت بکە',
      'ach_liked_desc': '@count کتێب دڵخواز بکە',
      'ach_polyglot_desc': 'بە @count زمانی جیاواز کتێب بخوێنەوە',
      'ach_time_desc': 'بۆ ماوەی @count کاتژمێر فێربە',
      'total_study_time': 'تێکڕای کاتی فێربوون',
      'show_text': 'پیشاندانی دەق',
      'hide_text': 'شاردنەوەی دەق',
      'family_plan_desc': 'ئەندامانی خێزانەکەت ببەستەوە بۆ هاوبەشکردنی سنوورەکانی کورتەکراوەی پڕیمیۆم و هاوکاتکردنی زنجیرە ڕۆژەکانت.',
      'family_plan_active': 'پلانی خێزان چالاکە',
      'family_plan_limit_desc': 'تۆ پێشتر ئەندامێکی خێزانەکەت بەستووەتەوە. تکایە پەیوەندی بە بەشی پشتیوانییەوە بکە ئەگەر پێویستت بە گۆڕین یان ڕاستکردنەوەی ئەم ناونیشانی ئیمەیڵەیە.',
      'family_member_email_hint': 'ئیمەیڵی ئەندامی خێزان...',
      'family_link_btn': 'ببەستەوە',
      'family_linked_members': 'ئەندامە بەستراوەکان',
      'family_invalid_email': 'ناونیشانی ئیمەیڵ دروست نییە',
      'family_linked_toast': 'بە سەرکەوتوویی {email} بە پلانی خێزانەکەتەوە بەسترا!',
      'sequence_of_books': 'ڕیزبەندیی پەرتووکەکان',
      'cert_completion': 'بڕوانامەی تەواوکردن',
      'presented_to': 'ئەم بڕوانامەیە بە شانازییەوە پێشکەش دەکرێت بە:',
      'completed_learning_path': 'بۆ تەواوکردنی ڕێگەی فێربوونی:',
      'download_share': 'داگرتنی PDF / بڵاوکردنەوە',
      'claim_cert': 'وەرگرتنی بڕوانامەی تەواوکردن',
      'guest_reader': 'خوێنەری میوان',
      'read': 'خوێندنەوە',
      'listen': 'گوێگرتن',
      'overview': 'تێڕوانینی گشتی',
      'related_summaries': 'پوختە پەیوەندیدارەکان',
      'premium': 'پڕیمیۆم',
      'removed_from_library': 'لە کتێبخانە سڕایەوە',
      'saved_to_library': 'لە کتێبخانە پاشەکەوت کرا',
      'removed_from_liked': 'لە لیستی دڵخوازەکان سڕایەوە',
      'added_to_liked': 'بۆ لیستی دڵخوازەکان زیادکرا',
      'sharing_copied': 'لینکی بڵاوکردنەوە کۆپی کرا!',
      'downloaded_success': 'بە سەرکەوتوویی داگیرا بۆ خوێندنەوەی بەبێ هێڵ',
      'downloaded_failed': 'داگرتن سەرکەوتوو نەبوو. هێڵی ئینتەرنێتەکەت بپشکنە.',
      'duration': 'ماوە',
      'key_objective': 'ئامانجی سەرەکی',
      'mins_suffix': 'خولەک',
      'text_only': 'تەنها دەق',
      'previous': 'پێشوو',
      'next_chapter': 'خاڵی سەرەکی دواتر',
      'finish_book': 'تەواوکردنی کتێب',
      'note_added': 'تێبینی زیادکرا!',
      'add_personal_note': 'زیادکردنی تێبینیی کەسی',
      'note_hint': 'تێبینی یان تێڕوانینی خۆت بنووسە...',
      'save_note': 'پاشەکەوتکردنی تێبینی',
      'listen_chapter': 'گوێگرتن لەم خاڵە سەرەکییە',
      'no_chapters_warning': 'هیچ پوختەیەکی خاڵە سەرەکییەکان بەم زمانە دابین نەکراوە.',
      'digest': 'پوختە',
      'tag_focus': 'سەرنج',
      'tag_productivity': 'بەرهەمداری',
      'tag_success': 'سەرکەوتن',
      'tag_history': 'مێژوو',
      'tag_kurdish': 'کوردی',
      'tag_science': 'زانست',
      'tag_philosophy': 'فەلسەفە',
      'no_summaries_found': 'هیچ پوختەیەک نەدۆزرایەوە',
      'no_books_in_progress': 'هیچ کتێبێک لە ئێستادا لە خوێندندا نییە.',
      'no_liked_books': 'تۆ هێشتا هیچ کتێبێکت دڵخواز نەکردووە.',
      'saved_library_empty': 'کتێبخانەی پاشەکەوتکراوت بەتاڵە.',
      'no_finished_books': 'تۆ هێشتا هیچ کتێبێکت تەواو نەکردووە.',
      'offline_storage_enabled': 'خوێندنەوەی بەبێ هێڵ چالاکە',
      'no_offline_summaries': 'هیچ پوختەیەکی داگیراو نییە.',
      'streak_congrats': 'پیرۆزە!',
      'streak_title_singular': '١ ڕۆژ بەردەوامی!',
      'streak_title_plural': '{count} ڕۆژ بەردەوامی!',
      'streak_message': 'بۆ پاراستنی زنجیرەکەت، دەبێت هەموو ڕۆژێک ٤ بیرۆکەی سەرەکی یان کتێبێکی تەواو بخوێنیتەوە یان گوێ لێ بگریت. ئەگەر ڕۆژێک لەدەست بدەیت، دەگەڕێتەوە بۆ ٠.',
      'update_available': 'وەشانی نوێ بەردەستە',
      'update_desc': 'وەشانێکی نوێی پەرتوک بەردەستە. تکایە ئەپەکە نوێ بکەرەوە بۆ بەردەوامبوون لە چێژوەرگرتن لە دوایین پوختەکان و تایبەتمەندییەکان.',
      'update_now': 'ئێستا نوێ بکەرەوە',
      'later': 'دواتر',
      'premium_expired_title': 'پریمیۆم بەسەرچوو',
      'premium_expired_desc': 'بەشداری پریمیۆمەکەت بەسەرچوو. بەشدارییەکەت نوێ بکەرەوە بۆ کردنەوەی خوێندنەوە، گوێگرتن، و دابەزاندنی بێسنوور.',
      'renew_now': 'ئێستا نوێ بکەرەوە',
      'no_notes_saved': 'هیچ تێبینییەک پاشەکەوت نەکراوە.',
      'no_highlights_saved': 'هیچ نیشانکردنێک پاشەکەوت نەکراوە.',
      'flashcard_question': 'پرسیار',
      'flashcard_answer': 'وەڵام',
      'flip_card': 'هەڵگەڕاندنەوەی کارت',
      'session_completed': 'خولەکە کۆتایی هات!',
      'flashcards_completed_desc': 'بە سەرکەوتوویی پێداچوونەوەت بۆ هەموو فلاشکاردەکانی ئەم کورتەکراوەیە کرد.',
      'awesome': 'ناوازەیە',
      'card_progress': 'کارتی {current} لە {total}',
      'no_flashcards': 'هێشتا هیچ فلاشکاردێک بۆ ئەم کورتەکراوەیە بەردەست نییە.',
      'quiz_completed': 'تاقیکردنەوەکە کۆتایی هات!',
      'your_score': 'نمرەکەت: {score} لە {total}',
      'quiz_score_desc': 'تۆ {percent}% وەڵامی ڕاستت داوەتەوە! زنجیرەی ڕۆژانەت درێژکرایەوە.',
      'return_to_summary': 'گەڕانەوە بۆ کورتەکراوە',
      'no_quizzes': 'هێشتا هیچ پرسیارێکی تاقیکردنەوە بۆ ئەم کورتەکراوەیە نییە.',
      'submit_answer': 'ناردنی وەڵام',
      'next_question': 'پرسیاری دواتر',
      'view_results': 'بینینی ئەنجامەکان',
      'notifications_enabled': 'ئاگادارکردنەوە چالاککرا',
      'subscribe_now': 'ئێستا بەشدار ببە',
      'annual_plan': 'پلانی ساڵانە',
      'annual_price_desc': '٣٩\$ / ساڵ',
      'annual_trial_desc': 'هەر کاتێک بێت هەڵیوەشێنەرەوە',
      'save_percent': '٦٧٪ پاشەکەوت بکە',
      'paywall_feat_1': 'کردنەوەی سەدان کورتەکراوەی باشترین پەرتووکەکان',
      'paywall_feat_2': 'دەنگی کوالیتی بەرز و خوێنەری جۆراوجۆر',
      'paywall_feat_3': 'خوێندنەوەی دەرەوەی هێڵ و داگرتنی بێسنوور',
      'paywall_feat_4': 'فلاشکارد و پرسیار لە کۆتایی هەر پەرتووکێکدا',
      'paywall_feat_5': 'پەرتووک ڕۆژانە بە هەرسێ زمان زیاد دەکرێت',
      'paywall_feat_6': 'هەڵبژاردنی هاوبەشکردنی خێزانی تێدایە',
      'welcome_premium': 'بەخێربێیت بۆ پلانی تایبەتی (پڕیمیۆم)ی بارتوک!',
      'restore_success': 'بەشداریکردنەکان بە سەرکەوتوویی گەڕێندرانەوە!',
      'register_required_title': 'تۆمارکردن پێویستە',
      'register_required_desc': 'تکایە سەرەتا خۆت تۆمار بکە چونکە وەک میوان چوویتەتە ژوورەوە، پاشان بگەڕێوە ئێرە بۆ کڕینی بەشداری.',
    },
    'ar': {
      'app_name': 'بارتوك',
      'tagline': 'ملخصات مميزة وتعلم سريع',
      'splash_subtitle': 'تعلم بذكاء، وانمُ أسرع',
      'onboarding_title_1': 'معرفة ذات مستوى عالمي',
      'onboarding_desc_1': 'احصل على آلاف الأفكار الرئيسية من أفضل الكتب في العالم بنصوص وتسجيلات صوتية عالية الجودة.',
      'onboarding_title_2': 'نمو في 15 دقيقة',
      'onboarding_desc_2': 'استغل وقتك بذكاء. اقرأ أو استمع إلى ملخصات الكتب الكاملة أثناء تنقلاتك اليومية أو فترات الراحة.',
      'onboarding_title_3': 'مخصص لك خصيصاً',
      'onboarding_desc_3': 'احصل على اقتراحات يومية، وملخصات تناسب مزاجك، ومسارات تعليمية مخصصة من مدرب الذكاء الاصطناعي.',
      'get_started': 'ابدأ الآن',
      'next': 'التالي',
      'skip': 'تخطي',
      'select_language': 'اختر اللغة',
      'english': 'الإنجليزية',
      'kurdish': 'الكردية (السورانية)',
      'arabic': 'العربية',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'fullname': 'الاسم الكامل',
      'forgot_password': 'هل نسيت كلمة المرور؟',
      'login_with_google': 'متابعة باستخدام Google',
      'login_with_apple': 'متابعة باستخدام Apple',
      'continue_as_guest': 'متابعة كضيف',
      'dont_have_account': 'ليس لديك حساب؟ سجل الآن',
      'already_have_account': 'لديك حساب بالفعل؟ سجل الدخول',
      'select_interests': 'ما هي اهتماماتك؟',
      'interests_subtitle': 'سنقوم بتخصيص تجربة التعلم الخاصة بك بناءً على هذه الاختيارات.',
      'select_goals': 'اختر أهدافك التعليمية',
      'goals_subtitle': 'ضع أهدافاً لعادات التعلم اليومية الخاصة بك.',
      'save_continue': 'حفظ ومتابعة',
      'home': 'الرئيسية',
      'explore': 'استكشف',
      'search': 'بحث عن كتب',
      'library': 'مكتبتي',
      'reader_settings': 'إعدادات القارئ',
      'font_size': 'حجم الخط',
      'reader_theme': 'مظهر القراءة',
      'profile': 'الملف الشخصي',
      'daily_digest': 'الملخص اليومي',
      'digest_subtitle': 'قراءتك المختارة لليوم في 15 دقيقة',
      'mood_suggestions': 'كيف تشعر اليوم؟',
      'mood_ambitious': 'طموح',
      'mood_tired': 'متعب',
      'mood_curious': 'فضولي',
      'mood_stressed': 'مجهد',
      'streak_title': 'سلسلة التعلم اليومية',
      'streak_desc': 'استمر في التعلم يومياً للحفاظ على سلسلتك مستمرة!',
      'days_streak': 'أيام متتالية',
      'categories': 'التصنيفات',
      'saved_summaries': 'الملخصات المحفوظة',
      'downloads': 'التحميلات',
      'notes_highlights': 'الملاحظات والاضاءات',
      'learning_paths': 'مسارات التعلم',
      'achievements': 'الإنجازات',
      'settings': 'الإعدادات',
      'admin_dashboard': 'لوحة التحكم للمشرف',
      'premium_subscription': 'الاشتراك المميز',
      'go_premium': 'ترقية إلى الحساب المميز',
      'go_premium_desc': 'احصل على ملخصات غير محدودة، وتعليق صوتي، وتحميلات دون اتصال، وتدريب ذكي مخصص.',
      'start_free_trial': 'ابدأ الفترة التجريبية مجاناً',
      'restore_purchases': 'استعادة المشتريات',
      'book_details': 'تفاصيل الكتاب',
      'read_summary': 'اقرأ الملخص',
      'listen_audio': 'استمع للصوت',
      'five_min_summary': 'ملخص ٥ دقائق',
      'fifteen_min_summary': 'ملخص ١٥ دقيقة',
      'chapters': 'النقاط الرئيسية',
      'key_ideas': 'الأفكار الرئيسية',
      'keypoints_count': '{count} أفكار رئيسية',
      'key_quotes': 'الاقتباسات الرئيسية',
      'action_points': 'نقاط العمل',
      'ai_coach': 'مدرب الذكاء الاصطناعي',
      'ask_coach': 'اسأل المدرب سؤالاً...',
      'comparison': 'مقارنة الكتب',
      'quiz': 'ابدأ الاختبار',
      'flashcards': 'بطاقات الاستذكار',
      'add_note': 'أضف ملاحظة',
      'highlights': 'الإضاءات والمظلات',
      'my_notes': 'ملاحظاتي',
      'daily_streak': 'التفاعل المتتالي',
      'settings_dark_mode': 'المظهر الداكن',
      'settings_light_mode': 'المظهر الفاتح',
      'settings_notifications': 'الإشعارات',
      'settings_family': 'حسابات العائلة',
      'voice_narration': 'صوت القارئ',
      'save_goal': 'حفظ كهدف شخصي',
      'completed': 'مكتمل',
      'progress': 'التقدم',
      'certificate': 'شهادة إنجاز',
      'congratulations': 'تهانينا!',
      'cert_desc': 'لقد أتممت مسار التعلم هذا بنجاح!',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'add_new_book': 'إضافة كتاب جديد',
      'admin_mode': 'وضع المشرف',
      'title': 'العنوان',
      'author': 'الكاتب',
      'audio_url': 'رابط الملف الصوتي',
      'category': 'التصنيف',
      'is_premium_q': 'هل هو مميز؟',
      'upload': 'رفع المحتوى',
      'unlock_full_book': 'افتح الكتاب كاملاً',
      'guest_restriction_desc': 'تقتصر حسابات الضيوف على الوصول إلى أول نقطتين رئيسيتين فقط. أنشئ حسابًا مجانيًا للاستماع إلى الكتاب كاملاً.',
      'maybe_later': 'ربما لاحقاً',
      'chapter': 'النقطة الرئيسية',
      'exit_title': 'خروج من التطبيق',
      'exit_desc': 'هل أنت متأكد من رغبتك في الخروج من التطبيق؟',
      'exit_btn': 'خروج',
      'cancel_btn': 'إلغاء',
      'register_now': 'سجل الآن',
      'continue_reading': 'متابعة القراءة',
      'liked': 'أعجبني',
      'one_idea_per_day': 'فكرة واحدة يومياً',
      'my_learning_hub': 'مركز التعلم الخاص بي',
      'system_settings': 'إعدادات النظام',
      'sign_out': 'تسجيل الخروج',
      'popular_searches': 'عمليات البحث الشائعة',
      'recent_searches': 'عمليات البحث الأخيرة',
      'new_releases': 'الإصدارات الجديدة',
      'trending': 'الأكثر رواجاً',
      'editor_picks': 'اختيارات المحرر',
      'min_read': 'دقيقة قراءة',
      'streak': 'سلسلة التعلم',
      'ach_books_desc': 'أكمل @count كتب',
      'ach_streak_desc': 'حافظ على سلسلة لمدة @count أيام',
      'ach_saved_desc': 'احفظ @count كتب في مكتبتك',
      'ach_liked_desc': 'أعجب بـ @count كتب',
      'ach_polyglot_desc': 'اقرأ كتباً بـ @count لغات',
      'ach_time_desc': 'تعلم لما مجموعه @count ساعة',
      'total_study_time': 'إجمالي وقت الدراسة',
      'show_text': 'عرض النص',
      'hide_text': 'إخفاء النص',
      'family_plan_desc': 'قم بربط أفراد العائلة لمشاركة حدود الملخصات المميزة ومزامنة أيام التفاعل المتتالية.',
      'family_plan_active': 'خطة العائلة نشطة',
      'family_plan_limit_desc': 'لقد قمت بالفعل بربط أحد أفراد العائلة. يرجى الاتصال بالدعم إذا كنت بحاجة إلى تغيير أو تصحيح عنوان البريد الإلكتروني هذا.',
      'family_member_email_hint': 'البريد الإلكتروني لفرد العائلة...',
      'family_link_btn': 'ربط',
      'family_linked_members': 'الأعضاء المرتبطون',
      'family_invalid_email': 'عنوان البريد الإلكتروني غير صالح',
      'family_linked_toast': 'تم ربط {email} بخطة العائلة الخاصة بك!',
      'sequence_of_books': 'تسلسل الكتب',
      'cert_completion': 'شهادة إتمام',
      'presented_to': 'هذه الشهادة مقدمة بكل فخر إلى:',
      'completed_learning_path': 'لإتمام مسار التعلم:',
      'download_share': 'تحميل ملف PDF / مشاركة',
      'claim_cert': 'الحصول على شهادة الإتمام',
      'guest_reader': 'قارئ ضيف',
      'read': 'قراءة',
      'listen': 'استماع',
      'overview': 'نظرة عامة',
      'related_summaries': 'ملخصات ذات صلة',
      'premium': 'مميز',
      'removed_from_library': 'تمت الإزالة من المكتبة',
      'saved_to_library': 'تم الحفظ في المكتبة',
      'removed_from_liked': 'تمت الإزالة من الكتب المفضلة',
      'added_to_liked': 'تمت الإضافة إلى الكتب المفضلة',
      'sharing_copied': 'تم نسخ رابط المشاركة!',
      'downloaded_success': 'تم التحميل بنجاح للقراءة دون اتصال',
      'downloaded_failed': 'فشل التحميل. تحقق من الاتصال.',
      'duration': 'المدة',
      'key_objective': 'الهدف الرئيسي',
      'mins_suffix': 'دقيقة',
      'text_only': 'نص فقط',
      'previous': 'السابق',
      'next_chapter': 'النقطة الرئيسية التالية',
      'finish_book': 'إنهاء الكتاب',
      'note_added': 'تمت إضافة الملاحظة!',
      'add_personal_note': 'إضافة ملاحظة شخصية',
      'note_hint': 'اكتب تعليقك أو فكرتك هنا...',
      'save_note': 'حفظ الملاحظة',
      'listen_chapter': 'الاستماع إلى هذه النقطة',
      'no_chapters_warning': 'لا توجد ملخصات للنقاط الرئيسية متوفرة بهذه اللغة.',
      'digest': 'موجز',
      'tag_focus': 'التركيز',
      'tag_productivity': 'الإنتاجية',
      'tag_success': 'النجاح',
      'tag_history': 'التاريخ',
      'tag_kurdish': 'الكردية',
      'tag_science': 'العلوم',
      'tag_philosophy': 'الفلسفة',
      'no_summaries_found': 'لم يتم العثور على ملخصات',
      'no_books_in_progress': 'لا توجد كتب قيد القراءة حالياً.',
      'no_liked_books': 'لم تقم بالإعجاب بأي كتب بعد.',
      'saved_library_empty': 'مكتبتك المحفوظة فارغة.',
      'no_finished_books': 'لم تنهِ أي كتب بعد.',
      'offline_storage_enabled': 'تم تمكين التخزين دون اتصال',
      'no_offline_summaries': 'لا توجد ملخصات دون اتصال.',
      'streak_congrats': 'تهانينا!',
      'streak_title_singular': 'سلسلة يوم واحد!',
      'streak_title_plural': 'سلسلة {count} أيام!',
      'streak_message': 'للحفاظ على تقدمك، يجب عليك إكمال ٤ أفكار رئيسية أو كتاب كامل كل يوم. إذا فاتك يوم، فستعود السلسلة إلى ٠.',
      'update_available': 'تحديث جديد متوفر',
      'update_desc': 'يتوفر إصدار جديد من بارتوك. يرجى تحديث التطبيق للاستمرار في الاستمتاع بأحدث الملخصات والميزات.',
      'update_now': 'تحديث الآن',
      'later': 'لاحقاً',
      'premium_expired_title': 'انتهى الاشتراك المميز',
      'premium_expired_desc': 'لقد انتهى اشتراكك المميز. جدد اشتراكك اليوم لفتح القراءة والاستماع غير المحدود والتنزيلات دون اتصال بالإنترنت.',
      'renew_now': 'جدد الآن',
      'no_notes_saved': 'لم يتم حفظ أي ملاحظات بعد.',
      'no_highlights_saved': 'لم يتم حفظ أي إضاءات بعد.',
      'flashcard_question': 'السؤال',
      'flashcard_answer': 'الإجابة',
      'flip_card': 'اقلب البطاقة',
      'session_completed': 'اكتملت الجلسة!',
      'flashcards_completed_desc': 'لقد راجعت بنجاح جميع بطاقات الاستذكار لهذا الملخص.',
      'awesome': 'رائع',
      'card_progress': 'البطاقة {current} من {total}',
      'no_flashcards': 'لا توجد بطاقات استذكار متوفرة لهذا الملخص بعد.',
      'quiz_completed': 'اكتمل الاختبار!',
      'your_score': 'درجتك: {score} من {total}',
      'quiz_score_desc': 'لقد أجبت بنسبة {percent}% بشكل صحيح! تم تمديد سلسلة نشاطك اليومي.',
      'return_to_summary': 'العودة إلى الملخص',
      'no_quizzes': 'لا توجد أسئلة اختبار متوفرة لهذا الملخص بعد.',
      'submit_answer': 'إرسال الإجابة',
      'next_question': 'السؤال التالي',
      'view_results': 'عرض النتائج',
      'notifications_enabled': 'تم تفعيل الإشعارات',
      'subscribe_now': 'اشترك الآن',
      'annual_plan': 'الخطة السنوية',
      'annual_price_desc': '٣٩\$ / سنة',
      'annual_trial_desc': 'إلغاء في أي وقت',
      'save_percent': 'توفير ٦٧٪',
      'paywall_feat_1': 'فتح مئات من ملخصات الكتب المميزة',
      'paywall_feat_2': 'صوت عالي الجودة وقراء متنوعون',
      'paywall_feat_3': 'القراءة دون اتصال وتحميل غير محدود',
      'paywall_feat_4': 'بطاقات الاستذكار والأسئلة في نهاية كل كتاب',
      'paywall_feat_5': 'يتم إضافة كتب يومياً بجميع اللغات الثلاث',
      'paywall_feat_6': 'خيار مشاركة العائلة متضمن',
      'welcome_premium': 'مرحباً بك في بارتوك المميز!',
      'restore_success': 'تم استعادة المشتريات بنجاح!',
      'register_required_title': 'التسجيل مطلوب',
      'register_required_desc': 'يرجى تسجيل حساب أولاً لأنك مسجل كضيف، ثم العودة هنا لإجراء الشراء.',
    },
    'en': {
      'app_name': 'Partwk',
      'tagline': 'Premium summaries and fast learning',
      'splash_subtitle': 'Learn smarter, grow faster',
      'onboarding_title_1': 'World-Class Knowledge',
      'onboarding_desc_1': 'Get thousands of key ideas from the world\'s best books in high-quality text and audio.',
      'onboarding_title_2': 'Growth in 15 Minutes',
      'onboarding_desc_2': 'Use your time wisely. Read or listen to full book summaries during your daily commute or breaks.',
      'onboarding_title_3': 'Tailored Just For You',
      'onboarding_desc_3': 'Get daily suggestions, mood-based summaries, and personalized learning paths from our AI coach.',
      'get_started': 'Get Started',
      'next': 'Next',
      'skip': 'Skip',
      'select_language': 'Select Language',
      'english': 'English',
      'kurdish': 'Kurdish (Sorani)',
      'arabic': 'Arabic',
      'login': 'Login',
      'register': 'Create Account',
      'email': 'Email',
      'password': 'Password',
      'fullname': 'Full Name',
      'forgot_password': 'Forgot Password?',
      'login_with_google': 'Continue with Google',
      'login_with_apple': 'Continue with Apple',
      'continue_as_guest': 'Continue as Guest',
      'dont_have_account': 'Don\'t have an account? Register now',
      'already_have_account': 'Already have an account? Login',
      'select_interests': 'What are your interests?',
      'interests_subtitle': 'We\'ll tailor your learning experience based on these.',
      'select_goals': 'Select your learning goals',
      'goals_subtitle': 'Set daily goals for your learning habits.',
      'save_continue': 'Save and Continue',
      'home': 'Home',
      'explore': 'Explore',
      'search': 'Search',
      'library': 'My Library',
      'reader_settings': 'Reader Settings',
      'font_size': 'Font Size',
      'reader_theme': 'Reader Theme',
      'profile': 'Profile',
      'daily_digest': 'Daily Digest',
      'digest_subtitle': 'Your curated reading for today in 15 minutes',
      'mood_suggestions': 'How are you feeling today?',
      'mood_ambitious': 'Ambitious',
      'mood_tired': 'Tired',
      'mood_curious': 'Curious',
      'mood_stressed': 'Stressed',
      'streak_title': 'Learning Streak',
      'streak_desc': 'Keep learning every day to maintain your streak!',
      'days_streak': 'Day Streak',
      'categories': 'Categories',
      'saved_summaries': 'Saved Summaries',
      'downloads': 'Downloads',
      'notes_highlights': 'Notes & Highlights',
      'learning_paths': 'Learning Paths',
      'achievements': 'Achievements',
      'settings': 'Settings',
      'admin_dashboard': 'Admin Dashboard',
      'premium_subscription': 'Premium Subscription',
      'go_premium': 'Go Premium',
      'go_premium_desc': 'Get unlimited summaries, audio narration, offline downloads, and personalized AI coaching.',
      'start_free_trial': 'Start Free Trial',
      'restore_purchases': 'Restore Purchases',
      'book_details': 'Book Details',
      'read_summary': 'Read Summary',
      'listen_audio': 'Listen to Audio',
      'five_min_summary': '5 Min Summary',
      'fifteen_min_summary': '15 Min Summary',
      'chapters': 'Key Points',
      'key_ideas': 'Key Ideas',
      'keypoints_count': '{count} key points',
      'key_quotes': 'Key Quotes',
      'action_points': 'Action Points',
      'ai_coach': 'AI Learning Coach',
      'ask_coach': 'Ask the coach a question...',
      'comparison': 'Compare Books',
      'quiz': 'Take Quiz',
      'flashcards': 'Flashcards',
      'add_note': 'Add Note',
      'highlights': 'Highlights',
      'my_notes': 'My Notes',
      'daily_streak': 'Daily Streak',
      'settings_dark_mode': 'Dark Mode',
      'settings_light_mode': 'Light Mode',
      'settings_notifications': 'Notifications',
      'settings_family': 'Family Plan Accounts',
      'voice_narration': 'Voice Narration',
      'save_goal': 'Save as personal goal',
      'completed': 'Completed',
      'progress': 'Progress',
      'certificate': 'Certificate',
      'congratulations': 'Congratulations!',
      'cert_desc': 'You have successfully completed this learning path.',
      'save': 'Save',
      'cancel': 'Cancel',
      'add_new_book': 'Upload New Book',
      'admin_mode': 'Admin Mode',
      'title': 'Title',
      'author': 'Author',
      'audio_url': 'Audio URL',
      'category': 'Category',
      'is_premium_q': 'Is this premium?',
      'upload': 'Upload Content',
      'unlock_full_book': 'Unlock full book',
      'guest_restriction_desc': 'Guest accounts only have access to the first two key points. Create a free account to listen to the full book.',
      'maybe_later': 'Maybe Later',
      'chapter': 'Key Point',
      'exit_title': 'Exit App',
      'exit_desc': 'Are you sure you want to exit the app?',
      'exit_btn': 'Exit',
      'cancel_btn': 'Cancel',
      'register_now': 'Register Now',
      'continue_reading': 'Continue Reading',
      'liked': 'Liked',
      'one_idea_per_day': 'One Idea Per Day',
      'my_learning_hub': 'My Learning Hub',
      'system_settings': 'System Settings',
      'sign_out': 'Sign Out',
      'popular_searches': 'Popular Searches',
      'recent_searches': 'Recent Searches',
      'new_releases': 'New Releases',
      'trending': 'Trending',
      'editor_picks': 'Editor Picks',
      'min_read': 'min read',
      'streak': 'streak',
      'ach_books_desc': 'Complete @count books',
      'ach_streak_desc': 'Maintain a @count day streak',
      'ach_saved_desc': 'Save @count books to your library',
      'ach_liked_desc': 'Like @count books',
      'ach_polyglot_desc': 'Read books in @count languages',
      'ach_time_desc': 'Learn for @count total hours',
      'total_study_time': 'Total Study Time',
      'show_text': 'Show text',
      'hide_text': 'Hide text',
      'family_plan_desc': 'Link family members to share your premium summary limits and sync streaks.',
      'family_plan_active': 'Family Plan Active',
      'family_plan_limit_desc': 'You have already linked a family member. Please contact support if you need to alter or correct this email address.',
      'family_member_email_hint': 'Family member email...',
      'family_link_btn': 'Link',
      'family_linked_members': 'Linked Members',
      'family_invalid_email': 'Invalid email address',
      'family_linked_toast': 'Linked {email} to your Family Plan!',
      'sequence_of_books': 'Sequence of Books',
      'cert_completion': 'CERTIFICATE OF COMPLETION',
      'presented_to': 'This is proudly presented to:',
      'completed_learning_path': 'For completing the Learning Path:',
      'download_share': 'Download PDF / Share',
      'claim_cert': 'Claim Completion Certificate',
      'guest_reader': 'Guest Reader',
      'read': 'Read',
      'listen': 'Listen',
      'overview': 'Overview',
      'related_summaries': 'Related Summaries',
      'premium': 'PREMIUM',
      'removed_from_library': 'Removed from Library',
      'saved_to_library': 'Saved to Library',
      'removed_from_liked': 'Removed from Liked Books',
      'added_to_liked': 'Added to Liked Books',
      'sharing_copied': 'Sharing link copied to clipboard!',
      'downloaded_success': 'Downloaded successfully for offline access',
      'downloaded_failed': 'Failed to download. Check connection.',
      'duration': 'Duration',
      'key_objective': 'Key Objective',
      'mins_suffix': 'mins',
      'text_only': 'Text only',
      'previous': 'Previous',
      'next_chapter': 'Next Key Point',
      'finish_book': 'Finish Book',
      'note_added': 'Note added!',
      'add_personal_note': 'Add Personal Note',
      'note_hint': 'Type your reflection or insight...',
      'save_note': 'Save Note',
      'listen_chapter': 'Listen to Key Point',
      'no_chapters_warning': 'No key point summaries provided for this language.',
      'digest': 'DIGEST',
      'tag_focus': 'focus',
      'tag_productivity': 'productivity',
      'tag_success': 'success',
      'tag_history': 'history',
      'tag_kurdish': 'kurdish',
      'tag_science': 'science',
      'tag_philosophy': 'philosophy',
      'no_summaries_found': 'No summaries found',
      'no_books_in_progress': 'No books currently in progress.',
      'no_liked_books': "You haven't liked any books yet.",
      'saved_library_empty': 'Your saved library is empty.',
      'no_finished_books': "You haven't finished any books yet.",
      'offline_storage_enabled': 'Offline Storage Enabled',
      'no_offline_summaries': 'No offline summaries.',
      'streak_congrats': 'Congratulations!',
      'streak_title_singular': '1 Day Streak!',
      'streak_title_plural': '{count} Day Streak!',
      'streak_message': 'To keep your streak, you must finish 4 key points or a full book every day. If you miss a day, it resets back to 0.',
      'update_available': 'Update Available',
      'update_desc': 'A new version of Partwk is available. Please update to enjoy the latest summaries, audio narration, and features.',
      'update_now': 'Update Now',
      'later': 'Later',
      'premium_expired_title': 'Premium Expired',
      'premium_expired_desc': 'Your premium subscription has expired. Renew today to unlock unlimited reading, listening, and offline downloads.',
      'renew_now': 'Renew Now',
      'no_notes_saved': 'No notes saved yet.',
      'no_highlights_saved': 'No highlights saved yet.',
      'flashcard_question': 'Question',
      'flashcard_answer': 'Answer',
      'flip_card': 'Flip Card',
      'session_completed': 'Session Completed!',
      'flashcards_completed_desc': 'You have successfully reviewed all the active recall flashcards for this summary.',
      'awesome': 'Awesome',
      'card_progress': 'Card {current} of {total}',
      'no_flashcards': 'No flashcards available for this summary yet.',
      'quiz_completed': 'Quiz Completed!',
      'your_score': 'Your Score: {score} / {total}',
      'quiz_score_desc': 'You got {percent}% correct! Daily streak has been extended.',
      'return_to_summary': 'Return to summary',
      'no_quizzes': 'No quiz questions for this summary yet.',
      'submit_answer': 'Submit Answer',
      'next_question': 'Next Question',
      'view_results': 'View Results',
      'notifications_enabled': 'Notifications enabled.',
      'subscribe_now': 'Subscribe Now',
      'annual_plan': 'Annual Plan',
      'annual_price_desc': '\$39 / Year',
      'annual_trial_desc': 'Cancel anytime',
      'save_percent': 'SAVE 67%',
      'paywall_feat_1': 'Unlock 100s of top book summaries',
      'paywall_feat_2': 'High-Quality Audio & Dynamic Narrators',
      'paywall_feat_3': 'Offline Reads & Unlimited Downloads',
      'paywall_feat_4': 'Flash cards and questions at the end of each book',
      'paywall_feat_5': 'Books added daily in all 3 languages',
      'paywall_feat_6': 'Family Share Option Included',
      'welcome_premium': 'Welcome to Partwk Premium!',
      'restore_success': 'Purchases successfully restored!',
      'register_required_title': 'Registration Required',
      'register_required_desc': 'Please register first as you are logged in as a guest user and return here to purchase.',
    }
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }

  bool get isRtl => locale.languageCode == 'ku' || locale.languageCode == 'ar';
}

class AppLanguageState extends ChangeNotifier {
  Locale _locale = const Locale('en');
  Locale get locale => _locale;

  AppLanguageState() {
    _loadLocale();
  }

  void _loadLocale() async {
    final prefs = await SharedPreferences.getInstance();
    final String? langCode = prefs.getString('language_code');
    if (langCode != null) {
      _locale = Locale(langCode);
      notifyListeners();
    }
  }

  void setLanguage(String langCode) async {
    if (AppLocalizations.supportedLanguages.contains(langCode)) {
      _locale = Locale(langCode);
      notifyListeners();

      try {
        // Pause audio when switching language
        AppLocator.audio.pause();
      } catch (e) {
        // Audio service not yet initialized
      }

      final prefs = await SharedPreferences.getInstance();
      await prefs.setString('language_code', langCode);

      try {
        if (AppLocator.auth.currentUser != null) {
          await AppLocator.auth.updateSelectedLanguage(langCode);
        }
      } catch (e) {
        print("Error updating user selected language: $e");
      }
    }
  }

  bool get isRtl => _locale.languageCode == 'ku' || _locale.languageCode == 'ar';
  TextDirection get textDirection => isRtl ? TextDirection.rtl : TextDirection.ltr;
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLanguages.contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
